# Generated by Django 5.1.2 on 2024-12-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
    ]
