# Generated by Django 5.1.2 on 2024-10-28 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('posted_time', models.DateTimeField()),
                ('lang_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.language')),
            ],
        ),
    ]
