# Generated by Django 5.1.2 on 2024-10-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
