# Generated by Django 5.1.2 on 2024-10-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Advanced')], default=0)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('posted_time', models.DateTimeField()),
            ],
        ),
    ]
