# Generated by Django 5.1.2 on 2024-10-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_markquestion_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markquestion',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Advanced')], default=0),
        ),
    ]
