# Generated by Django 5.1.2 on 2024-12-25 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_rename_group_question_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='markquestion',
            name='done_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
