# Generated by Django 5.1.2 on 2025-01-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_likequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
