# Generated by Django 5.1.2 on 2025-01-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='like',
            new_name='likes',
        ),
    ]
