# Generated by Django 5.1.2 on 2024-10-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=31, primary_key=True, serialize=False)),
            ],
        ),
    ]
